// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An embedded DHCP/DHCPv6/RA server & NDP relay.
 *
 * ## Import
 *
 * Find the Terraform id from LuCI's JSON-RPC API. One way to find this information is with `curl` and `jq`# curl \
 *
 *  --data '{"id"0, "method""foreach", "params"["dhcp", "odhcpd"]}' \
 *
 *  http://192.168.1.1/cgi-bin/luci/rpc/uci?auth=$AUTH_TOKEN \
 *
 *  | jq '.result | map({terraformId.[".name"]})' # This command will output something like# [
 *
 *  {
 *
 *  "terraformId""cfg123456",
 *
 *  } ] # We'd then use the information to import the appropriate resource
 *
 * ```sh
 *  $ pulumi import openwrt:index/dhcpOdhcpd:DhcpOdhcpd this cfg123456
 * ```
 */
export class DhcpOdhcpd extends pulumi.CustomResource {
    /**
     * Get an existing DhcpOdhcpd resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DhcpOdhcpdState, opts?: pulumi.CustomResourceOptions): DhcpOdhcpd {
        return new DhcpOdhcpd(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openwrt:index/dhcpOdhcpd:DhcpOdhcpd';

    /**
     * Returns true if the given object is an instance of DhcpOdhcpd.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DhcpOdhcpd {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DhcpOdhcpd.__pulumiType;
    }

    /**
     * Location of the lease/hostfile for DHCPv4 and DHCPv6.
     */
    public readonly leasefile!: pulumi.Output<string>;
    /**
     * Location of the lease trigger script.
     */
    public readonly leasetrigger!: pulumi.Output<string>;
    /**
     * Enable DHCPv4 if the 'dhcp' section constains a `start` option, but no `dhcpv4` option set.
     */
    public readonly legacy!: pulumi.Output<boolean>;
    /**
     * Syslog level priority (0-7).
     */
    public readonly loglevel!: pulumi.Output<number>;
    /**
     * Use odhcpd as the main DHCPv4 service.
     */
    public readonly maindhcp!: pulumi.Output<boolean>;

    /**
     * Create a DhcpOdhcpd resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DhcpOdhcpdArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DhcpOdhcpdArgs | DhcpOdhcpdState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DhcpOdhcpdState | undefined;
            resourceInputs["leasefile"] = state ? state.leasefile : undefined;
            resourceInputs["leasetrigger"] = state ? state.leasetrigger : undefined;
            resourceInputs["legacy"] = state ? state.legacy : undefined;
            resourceInputs["loglevel"] = state ? state.loglevel : undefined;
            resourceInputs["maindhcp"] = state ? state.maindhcp : undefined;
        } else {
            const args = argsOrState as DhcpOdhcpdArgs | undefined;
            resourceInputs["leasefile"] = args ? args.leasefile : undefined;
            resourceInputs["leasetrigger"] = args ? args.leasetrigger : undefined;
            resourceInputs["legacy"] = args ? args.legacy : undefined;
            resourceInputs["loglevel"] = args ? args.loglevel : undefined;
            resourceInputs["maindhcp"] = args ? args.maindhcp : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DhcpOdhcpd.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DhcpOdhcpd resources.
 */
export interface DhcpOdhcpdState {
    /**
     * Location of the lease/hostfile for DHCPv4 and DHCPv6.
     */
    leasefile?: pulumi.Input<string>;
    /**
     * Location of the lease trigger script.
     */
    leasetrigger?: pulumi.Input<string>;
    /**
     * Enable DHCPv4 if the 'dhcp' section constains a `start` option, but no `dhcpv4` option set.
     */
    legacy?: pulumi.Input<boolean>;
    /**
     * Syslog level priority (0-7).
     */
    loglevel?: pulumi.Input<number>;
    /**
     * Use odhcpd as the main DHCPv4 service.
     */
    maindhcp?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a DhcpOdhcpd resource.
 */
export interface DhcpOdhcpdArgs {
    /**
     * Location of the lease/hostfile for DHCPv4 and DHCPv6.
     */
    leasefile?: pulumi.Input<string>;
    /**
     * Location of the lease trigger script.
     */
    leasetrigger?: pulumi.Input<string>;
    /**
     * Enable DHCPv4 if the 'dhcp' section constains a `start` option, but no `dhcpv4` option set.
     */
    legacy?: pulumi.Input<boolean>;
    /**
     * Syslog level priority (0-7).
     */
    loglevel?: pulumi.Input<number>;
    /**
     * Use odhcpd as the main DHCPv4 service.
     */
    maindhcp?: pulumi.Input<boolean>;
}
